import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { HoverCard } from './board/_components/hoverCard'
import { SideNav } from './board/_components/sidenav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='relative'>
          <SideNav />
          <div className='w-full pl-20'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
